apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: docbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: worker
          image: 100.87.103.100:8000/docbot/docbot-worker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: docbot-config
            - secretRef:
                name: docbot-secret
